add timeout detecting in simplersync

diff --git a/bin/simplersync b/bin/simplersync
--- a/bin/simplersync
+++ b/bin/simplersync
@@ -55,6 +55,7 @@ FULLLOGS=${FULLLOGS:-"false"}
 
 SIMPLE_RSYNC_OPTIONS=${SIMPLE_RSYNC_OPTIONS:-"-avH --delete-after --delay-updates"}
 SIMPLE_RSYNC_EXTRA=${SIMPLE_RSYNC_EXTRA:-""}
+RSYNC_MAX_RUNTIME=${RSYNC_MAX_RUNTIME:-7200}
 
 LOGDIR=${LOGDIR:-"${HOME}/log/${REPO}"}
 LOGFILE=${LOGFILE:-"${LOGDIR}/${NAME}.log"}
@@ -122,8 +123,20 @@ if ! ( set -o noclobber; echo "$$" > "${LOCKFILE}") 2> /dev/null; then
 		# Update the LOCKFILE
 		echo "$$" > "${LOCKFILE}"
 	else
-		echo "Unable to start rsync, lock file still exists, PID $(< ${LOCKFILE})"
-		exit 1
+		# Check if rsync has been running for too long
+		NOW=`date +%s`
+		LOCKSINCE=`stat -c %Y ${LOCKFILE}`
+		if (( $((NOW-LOCKSINCE)) > $RSYNC_MAX_RUNTIME )); then
+			log "Old rsync (PID `cat ${LOCKFILE}`) has been running longer than ${RSYNC_MAX_RUNTIME}s, killed."
+			# Kill the whole process group!
+			kill -`cat ${LOCKFILE}` 2> /dev/null
+			# Wait for a little moment to ensure the lock/log is done.
+			sleep 1
+		else
+			# Keep the old rsync running and we will exit.
+			echo "Unable to start rsync, lock file still exists, PID $(< ${LOCKFILE})"
+			exit 1
+		fi
 	fi
 fi
 
